import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import { needsYouPhrase } from "../vocabulary";

const SCREENS_SPEC = readFileSync(new URL("../../../e2e/screens.spec.ts", import.meta.url), "utf8");

/**
 * The e2e smoke test proves the front door reaches the real app by matching the
 * home headline. That headline is generated by `needsYouPhrase`, but the
 * assertion is a regex literal in a Playwright spec — so the two can drift, and
 * did: #1045 consolidated four phrasings of this idea into the helper, the spec
 * kept asserting the retired "waiting on you", and `e2e` is a REQUIRED check.
 * Main went red and every open PR was blocked by a stale string in a test.
 *
 * This ties them together in the unit suite, which runs in seconds and fails
 * with a pointer to the file to edit — rather than in Playwright, minutes later,
 * on someone else's unrelated PR.
 */
describe("needsYouPhrase ↔ e2e front-door assertion", () => {
  const assertion = SCREENS_SPEC.match(/toContainText\((\/[^/]+\/i)\)/);

  it("still has an assertion to check", () => {
    expect(assertion?.[1], "the front-door assertion in e2e/screens.spec.ts moved or was removed").toBeDefined();
  });

  it("matches what the vocabulary actually renders", () => {
    const [, source] = assertion!;
    const re = new RegExp(source.slice(1, -2), "i");
    // Both branches of the helper, so a singular/plural change is caught too.
    for (const count of [1, 2, 7]) {
      expect(re.test(needsYouPhrase(count)), `e2e assertion ${source} does not match "${needsYouPhrase(count)}"`).toBe(true);
    }
  });

  it("still admits the signed-out branch", () => {
    // CI has no Supabase env, so root redirects to sign-in. If that alternative
    // is ever dropped from the regex the check passes locally and fails in CI.
    const [, source] = assertion!;
    expect(new RegExp(source.slice(1, -2), "i").test("Sign in")).toBe(true);
  });
});
