import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".claude/worktrees/**",
    ".worktrees/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase start` (i.e. `pnpm sandbox:up`) — minified edge
    // bundles. Already gitignored; without this, running the sandbox makes
    // `pnpm lint` fail on code nobody wrote.
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
