import {
  applyActivityFilters,
  buildActivitySummary,
  groupActivityEntriesByDay,
  mergeActivityEntries,
  type ActivityEntry,
  type ActivityQuery,
  type RecentActivity,
} from "./read-model";

/**
 * Read-only demo activity feed. Used when Supabase is not configured (local
 * preview) or when no real activity exists yet, so the Activity page renders a
 * populated, plain-English BSR audit trail instead of an empty state. Every
 * entry is display-only; nothing here triggers an outbound action.
 */

const MIN = 60_000;
const HOUR = 3_600_000;
const DAY = 86_400_000;

function iso(offsetMs: number): string {
  return new Date(Date.now() - offsetMs).toISOString();
}

type Seed = Omit<ActivityEntry, "occurredAt"> & { agoMs: number };

const SEEDS: Seed[] = [
  {
    id: "demo-act-1",
    kind: "draft",
    tone: "amber",
    title: "Generated 3 campaign concepts",
    predicate: "generated 3 campaign concepts",
    detail: "Pricing-Intent Fast Track 2026 — 3 angles drafted for review",
    actor: "Arc",
    actorType: "arc",
    category: "asset",
    insightLabel: "Needs you",
    relatedLabel: "Pricing-Intent Fast Track 2026",
    href: "/campaigns",
    agoMs: 22 * MIN,
  },
  {
    id: "demo-act-2",
    kind: "campaign",
    tone: "green",
    title: "Campaign approved",
    predicate: "approved a campaign",
    detail: "Quarterly Nurture Refresh 2026 brief approved and locked for build",
    actor: "Evan",
    actorType: "human",
    category: "campaign",
    insightLabel: "Marketing progress",
    relatedLabel: "Quarterly Nurture Refresh 2026",
    href: "/campaigns",
    agoMs: 48 * MIN,
  },
  {
    id: "demo-act-3",
    kind: "event",
    tone: "blue",
    title: "Lead updated",
    predicate: "updated a lead",
    detail: "Northwest Property Group moved to Qualified — lead score 88",
    actor: "Arc",
    actorType: "arc",
    category: "crm",
    insightLabel: "Customer signal",
    relatedLabel: "Northwest Property Group",
    href: "/crm/leads",
    agoMs: 1 * HOUR + 5 * MIN,
  },
  {
    id: "demo-act-4",
    kind: "run",
    tone: "green",
    title: "Run completed",
    predicate: "finished a run",
    detail: "Creative generation for Quarterly Nurture Refresh — 6 of 9 variants",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Agent work",
    relatedLabel: "Agent task",
    href: "/arc",
    agoMs: 1 * HOUR + 32 * MIN,
  },
  {
    id: "demo-act-5",
    kind: "draft",
    tone: "amber",
    title: "Persona insight added",
    predicate: "added a persona insight",
    detail: "Team Admin segment shows rising expansion urgency",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Agent work",
    relatedLabel: "Team Admin",
    href: "/personas",
    agoMs: 2 * HOUR + 10 * MIN,
  },
  {
    id: "demo-act-6",
    kind: "draft",
    tone: "red",
    title: "Integrity finding raised",
    predicate: "raised an integrity finding",
    detail: "Overclaim risk flagged in Pricing-Intent Fast Track ad headline",
    actor: "Arc",
    actorType: "arc",
    category: "risk",
    insightLabel: "Risk blocked",
    relatedLabel: "Pricing-Intent Fast Track 2026",
    href: "/arc",
    agoMs: 2 * HOUR + 40 * MIN,
  },
  {
    id: "demo-act-7",
    kind: "draft",
    tone: "amber",
    title: "Asset created",
    predicate: "created an asset",
    detail: "Customer Win-Back landing one-pager copy drafted",
    actor: "Arc",
    actorType: "arc",
    category: "asset",
    insightLabel: "Needs you",
    relatedLabel: "Customer Win-Back",
    href: "/campaigns",
    agoMs: 3 * HOUR + 15 * MIN,
  },
  {
    id: "demo-act-8",
    kind: "campaign",
    tone: "red",
    title: "Approval Declined",
    predicate: "declined a draft",
    detail: "Feature Adoption SMS declined — tone too aggressive, revise CTA",
    actor: "Evan",
    actorType: "human",
    category: "campaign",
    insightLabel: "Risk blocked",
    relatedLabel: "Feature Adoption Awareness",
    href: "/campaigns",
    agoMs: 4 * HOUR,
  },
  {
    id: "demo-act-9",
    kind: "draft",
    tone: "amber",
    title: "Revision requested",
    predicate: "asked for changes",
    detail: "Team Admin email batch — soften urgency, add proof point",
    actor: "Evan",
    actorType: "human",
    category: "approval",
    insightLabel: "Needs you",
    relatedLabel: "Team Admin Reactivation",
    href: "/campaigns",
    agoMs: 4 * HOUR + 50 * MIN,
  },
  {
    id: "demo-act-10",
    kind: "event",
    tone: "blue",
    title: "Company added",
    predicate: "added a company",
    detail: "Larkfield Partners flagged as high-fit referral partner",
    actor: "Arc",
    actorType: "arc",
    category: "crm",
    insightLabel: "Customer signal",
    relatedLabel: "Larkfield Partners",
    href: "/crm/companies",
    agoMs: 6 * HOUR,
  },
  {
    id: "demo-act-11",
    kind: "run",
    tone: "blue",
    title: "Run started",
    predicate: "started a run",
    detail: "Message-angle research for Referral Advisor Co-Marketing",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Agent work",
    relatedLabel: "Agent task",
    href: "/arc",
    agoMs: 7 * HOUR,
  },
  {
    id: "demo-act-12",
    kind: "event",
    tone: "blue",
    title: "Engagement signal received",
    predicate: "picked up an engagement signal",
    detail: "Pricing-page surge across high-intent accounts — expansion demand likely",
    actor: "Engagement Signals",
    actorType: "integration",
    category: "integration",
    insightLabel: "Customer signal",
    relatedLabel: "High-intent accounts",
    href: null,
    agoMs: 9 * HOUR,
  },
  {
    id: "demo-act-13",
    kind: "campaign",
    tone: "green",
    title: "Campaign package approved",
    predicate: "approved a campaign",
    detail: "Pricing-Intent Fast Track launch package approved and outbound-locked",
    actor: "Evan",
    actorType: "human",
    category: "campaign",
    insightLabel: "Marketing progress",
    relatedLabel: "Pricing-Intent Fast Track 2026",
    href: "/campaigns",
    agoMs: 1 * DAY + 1 * HOUR,
  },
  {
    id: "demo-act-14",
    kind: "draft",
    tone: "green",
    title: "Asset approved",
    predicate: "approved an asset",
    detail: "Solutions partner referral sheet approved for distribution prep",
    actor: "Evan",
    actorType: "human",
    category: "asset",
    insightLabel: "Marketing progress",
    relatedLabel: "Solutions Partner Program",
    href: "/campaigns",
    agoMs: 1 * DAY + 3 * HOUR,
  },
  {
    id: "demo-act-15",
    kind: "event",
    tone: "blue",
    title: "Contact updated",
    predicate: "updated a contact",
    detail: "Jordan Reyes (Ops Manager) confirmed as referral decision-maker",
    actor: "Arc",
    actorType: "arc",
    category: "crm",
    insightLabel: "Customer signal",
    relatedLabel: "Jordan Reyes",
    href: "/crm/contacts",
    agoMs: 1 * DAY + 5 * HOUR,
  },
  {
    id: "demo-act-16",
    kind: "run",
    tone: "green",
    title: "Run completed",
    predicate: "finished a run",
    detail: "Quarterly Nurture Refresh brief + audience plan generated",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Agent work",
    relatedLabel: "Agent task",
    href: "/arc",
    agoMs: 1 * DAY + 6 * HOUR,
  },
  {
    id: "demo-act-17",
    kind: "draft",
    tone: "amber",
    title: "Opportunity surfaced",
    predicate: "surfaced an opportunity",
    detail: "12 dormant multi-seat accounts flagged for re-engagement",
    actor: "Arc",
    actorType: "arc",
    category: "agent",
    insightLabel: "Needs you",
    relatedLabel: "Multi-seat segment",
    href: "/personas",
    agoMs: 1 * DAY + 9 * HOUR,
  },
  {
    id: "demo-act-18",
    kind: "campaign",
    tone: "amber",
    title: "Campaign submitted",
    predicate: "sent a campaign for approval",
    detail: "Renewal Manager Pre-Check tailored walkthrough offer submitted for review",
    actor: "Arc",
    actorType: "arc",
    category: "campaign",
    insightLabel: "Needs you",
    relatedLabel: "Renewal Manager Pre-Check",
    href: "/campaigns",
    agoMs: 2 * DAY,
  },
  {
    id: "demo-act-19",
    kind: "event",
    tone: "blue",
    title: "Outcome recorded",
    predicate: "recorded an outcome",
    detail: "Q1 pricing-intent campaign booked 14 demos — attribution logged",
    actor: "Arc",
    actorType: "arc",
    category: "crm",
    insightLabel: "Campaign result",
    relatedLabel: "Q1 Pricing-Intent",
    href: "/crm/outcomes",
    agoMs: 2 * DAY + 4 * HOUR,
  },
  {
    id: "demo-act-20",
    kind: "run",
    tone: "gray",
    title: "Heartbeat logged",
    predicate: "logged a heartbeat",
    detail: "Arc runner healthy — outbound actions remain locked",
    actor: "System",
    actorType: "system",
    category: "system",
    insightLabel: null,
    relatedLabel: "Arc runner",
    href: null,
    agoMs: 2 * DAY + 8 * HOUR,
  },
];

export function buildDemoActivity(query: ActivityQuery = {}): RecentActivity {
  const entries: ActivityEntry[] = SEEDS.map(({ agoMs, ...rest }) => ({ ...rest, occurredAt: iso(agoMs) }));
  const filtered = applyActivityFilters(entries, query);
  const merged = mergeActivityEntries(filtered, query.limit ?? 100);

  return {
    status: "live",
    entries: merged,
    summary: buildActivitySummary(merged),
    groups: groupActivityEntriesByDay(merged),
  };
}
